Employee
coronaJobs/backend pull request #41
Opened 2020-05-29 20:44 UTC by sgcarreno

2020-06-01 19:59 UTC, vaguila95 requested changes

2020-06-01 19:59 UTC, vaguila95 commented on src/graphQL/resolvers/employment.js
> +      }
En volaa esto podría ir en una validation

2020-06-01 19:59 UTC, vaguila95 commented on src/graphQL/resolvers/employment.js
> +      }
se usaría la misma validación ak :eyes:

2020-06-01 20:09 UTC, sgcarreno commented on src/graphQL/resolvers/employment.js
> +      }
Es que pensaba que estas líneas se iban a modificar con el 'can' (el segundo if al menos), entonces preferí esperar a que le pusiéramos 'can' a todo y ahí hacer el refactor. O no aplica el can acá? jajaja

2020-06-05 20:50 UTC, vaguila95 approved these changes

2020-06-05 20:51 UTC, merged