:sparkles: feat: evaluation for employees
coronaJobs/backend pull request #57
Opened 2020-06-17 13:34 UTC by cnscheihing

# Description
Evaluación para employees cuando un trabajo se ha finalizado (o pagado).
- Cambio modelo de `Employments` y migración.
- Anidación en `User` para entregar `comments` y `rating`.
- Resolver para crear Evaluación.
## Type of change
Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)
# How Has This Been Tested?
Please describe the tests that you ran to verify your changes (Like web browser's or mobile devices). Provide instructions so we can reproduce.
- [X] GraphQL Playground (local)
# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] The target of this commit is 'dev'

2020-06-17 17:51 UTC, sgcarreno requested changes
Hay que hacer un pequeño cambio pa que sirva después con el employer. (Ver comentarios en los archivos)

2020-06-17 17:51 UTC, sgcarreno commented on src/utils/user.js
> +      ratingName: "employerRating",
Este se tiene que llamar igual que el de la línea 16.

2020-06-17 17:51 UTC, sgcarreno commented on src/utils/user.js
> +      name: "employeeRating",
A este pongámosle ratingName en vez de name. Habría que cambiarlo en el resolver también.

2020-06-17 17:51 UTC, sgcarreno commented on src/graphQL/resolvers/user.js
> +        globalRating += employment[roleName.name];
Ver los comentarios de más abajo.

2020-06-20 21:45 UTC, cnscheihing commented on src/utils/user.js
> +      ratingName: "employerRating",
De acuerdo! Ya fue resuelto

2020-06-20 21:46 UTC, cnscheihing commented on src/utils/user.js
> +      name: "employeeRating",
De acuerdo! Ya fue resuelto

2020-06-20 21:46 UTC, cnscheihing commented on src/graphQL/resolvers/user.js
> +        globalRating += employment[roleName.name];
De acuerdo! Ya fue resuelto

2020-06-20 22:21 UTC, sgcarreno approved these changes

2020-06-20 22:32 UTC, merged